name: Build and Deploy GUI Helpers Jar
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build-Linux:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt-get -y install bluez libbluetooth-dev libdbus-1-dev
    - name: Build using Cmake
      id: cmake-build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release ..
        make
    - name: Locate .so files
      run: |
        cd $GITHUB_WORKSPACE
        find . -name "*.so*"
        ls -l java-package/openbci_gui_helpers/src/main/resources/
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      if: steps.cmake-build.outputs.exit_code == 0
      with:
        name: linux-artifacts
        path: java-package/openbci_gui_helpers/src/main/resources/
        retention-days: 1